version: '3.9'

services:
    openvpn:
        image: dperson/openvpn-client
        container_name: openvpn
        cap_add:
            - NET_ADMIN
        ports:
            - "443:443"
            - "80:80"
        devices: 
            - /dev/net/tun
        dns:
            - "8.8.8.8"
            - "192.168.178.253"
        volumes:
            - ./vpn:/vpn
        restart: always

    traefik:
        container_name: traefik
        image: traefik:v2.4
        volumes:
            - $PWD/traefik.toml:/traefik.toml
            - $PWD/acme.json:/acme.json
            - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.justAdummyService.loadbalancer.server.port=1337"
            - "traefik.http.routers.traefik.rule=Host(`traefik.forkbomb.dev`)"
            - "traefik.http.routers.traefik.entrypoints=websecure"
            - "traefik.http.routers.traefik.tls=true"
            - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
            - "traefik.http.routers.traefik.service=api@internal"
            - "traefik.http.routers.traefik.middlewares=auth"
            - "traefik.http.middlewares.auth.basicauth.users=USER:$$PASSWORD"
        depends_on:
            - openvpn

    helper:
        image: debian:buster
        container_name: helper
        network_mode: container:openvpn
        depends_on:
            - openvpn
