version: '3.9'

networks:
    cluster:
        name: cluster
          
services:
    vpnserver:
        image: hwdsl2/ipsec-vpn-server
        container_name: vpnserver
        restart: always
        privileged: true
        ports:
            - "500:500/udp"
            - "4500:4500/udp"
        networks:
            - cluster
        volumes:
            - ikev2vpndata:/etc/ipsec.d
            - $(pwd)/vpn.env:/opt/src/vpn.env:ro
        secrets:
            - vpn_ipsec_psk
            - vpn_users
            - vpn_passwords

volumes:
    ikev2vpndata:
        name: ikev2vpndata
