version: '3.9'

networks:
    cluster:
        name: cluster
          
services:
    vpnserver:
        image: hwdsl2/ipsec-vpn-server
        container_name: vpnserver
        restart: always
        privileged: true
        environment:
            - VPN_IPSEC_PSK=/run/secrets/vpn_ipsec_psk
            - VPN_USER=/run/secrets/vpn_users
            - VPN_PASSWORD=/run/secrets/vpn_passwords
        ports:
            - "500:500/udp"
            - "4500:4500/udp"
        networks:
            - cluster
        volumes:
            - ikev2vpndata:/etc/ipsec.d
        secrets:
            - vpn_ipsec_psk
            - vpn_users
            - vpn_passwords

volumes:
    ikev2vpndata:
        name: ikev2vpndata

secrets:
    vpn_ipsec_psk:
        file: ./dockerbuild/vpn/secrets/vpn_ipsec_psk
    vpn_users:
        file: ./dockerbuild/vpn/secrets/vpn_users
    vpn_passwords:
        file: ./dockerbuild/vpn/secrets/vpn_passwords
