version: '3.9'
          
services:
    openvpn:
        image: dperson/openvpn-client
        container_name: openvpn
        cap_add:
            - NET_ADMIN
        devices: 
            - /dev/net/tun
        volumes:
            - ./vpn:/vpn
        restart: always
