version: '3.9'
          
services:
    vpnserver:
        image: hwdsl2/ipsec-vpn-server
        container_name: vpnserver
        restart: always
        privileged: true
        network_mode: host
        volumes:
            - ikev2vpndata:/etc/ipsec.d
            - ./vpn.env:/opt/src/vpn.env:ro

volumes:
    ikev2vpndata:
        name: ikev2vpndata
