version: '3.9'

services:
    openvpn:
        image: dperson/openvpn-client
        container_name: openvpn
        cap_add:
            - NET_ADMIN
        devices: 
            - /dev/net/tun
        volumes:
            - ./vpn:/vpn
        restart: always

    traefik:
        container_name: traefik
        image: traefik:v2.0
        ports:
            - "81:80/tcp"
            - "8080:8080/tcp"
            - "444:443/tcp"
        volumes:
            - ./traefik.toml:/etc/traefik/traefik.toml
            - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            
            - "traefik.http.routers.traefik_https.rule=Host(`traefik.forkbomb.dev`)"
            - "traefik.http.routers.traefik_https.entrypoints=websecure"
            - "traefik.http.routers.traefik_https.tls=true"
            # - "traefik.http.routers.traefik_https.tls.certResolver=letsencrypt"
            - "traefik.http.routers.traefik_https.service=api@internal"
            - "traefik.http.routers.traefik_https.middlewares=traefik-auth"
            - "traefik.http.middlewares.auth.basicauth.users=USER:PASSWORD"

            - "traefik.http.routers.http_traefik.rule=Host(`traefik.forkbomb.dev`)"
            - "traefik.http.routers.http_traefik.entrypoints=web"
            - "traefik.http.routers.http_traefik.middlewares=https_redirect"
            - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
            - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
        depends_on:
            - openvpn

    helper:
        image: debian:buster
        container_name: helper
        network_mode: container:openvpn
        depends_on:
            - openvpn
