[entryPoints]
  [entryPoints.web]
  address = ":80"
  [entryPoints.web.http]
    [entryPoints.web.http.redirections]
      [entryPoints.web.http.redirections.entryPoint]
        to = "websecure"
        scheme = "https"
  [entryPoints.websecure]
  address = ":443"

[api]
  dashboard = true

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  exposedByDefault = false

[certificatesResolvers.letsencrypt.acme]
  email = "ben@forkbomb.dev"
  storage = "acme.json"
  caServer = "https://acme-v02.api.letsencrypt.org/directory"
  [certificatesResolvers.letsencrypt.acme.tlsChallenge]

[http]
  [http.services]
    [http.services.nextcloud.loadBalancer]
      [[http.services.nextcloud.loadBalancer.servers]]
        url = "http://192.168.178.253:8081/"
  [http.routers]
    [http.routers.nextcloud]
      rule = "Host(`nextcloud.forkbomb.dev`)"
      service = "nextcloud"
      [http.routers.nextcloud.tls]
        certResolver = "letsencrypt"
        [[http.routers.nextcloud.tls.domains]]
          main = "forkbomb.dev"
          sans = ["nextcloud.forkbomb.dev"]
