[entryPoints]
  [entryPoints.web]
  address = "0.0.0.0:80"
  [entryPoints.websecure]
  address = "0.0.0.0:443"

[api]
  dashboard = true

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "forkbomb.dev"
  watch = true
  exposedByDefault = false

[certificatesResolvers.letsencrypt.acme]
  email = "ben@forkbomb.dev"
  storage = "acme.json"
  [certificatesResolvers.letsencrypt.acme.tlsChallenge]
