[entryPoints]
    [entryPoints.web]
    address = "0.0.0.0:80"
    [entryPoints.websecure]
    address = "0.0.0.0:443"

[api]
    dashboard = true

[providers.docker]
    endpoint = "unix:///var/run/docker.sock"