version: '3.9'

networks:
    cluster:
        name: cluster
    lan:
        name: lan
        driver: macvlan
        driver_opts:
            parent: eth0
        ipam:
            config:
                - subnet: 192.168.178.0/24
          
services:
    maindb:
        build: dockerbuild/maindb
        image: my/maindb
        container_name: maindb
        ports:
            - "3306:3306"
        networks:
            - cluster
        volumes:
            - maindb:/var/lib/mysql
        restart: unless-stopped

    redis:
        image: arm32v7/redis
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - cluster
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        restart: unless-stopped

    traefik:
        container_name: traefik
        image: traefik:v2.0
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
        ports:
            - "80:80/tcp"
            - "8080:8080/tcp"
        networks:
            - cluster
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: unless-stopped
        
    nextcloud:
        image: nextcloud
        container_name: nextcloud
        ports:
            - "8081:80"
        networks:
            - cluster
        volumes:
            - nextcloud:/var/www/html
        environment:
            - MYSQL_HOST=maindb
            - MYSQL_PASSWORD=nextcloud
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud
            - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
            - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
            - NEXTCLOUD_TRUSTED_DOMAINS="localhost 192.168.178.253 nextcloud.forkbomb.dev nextcloud.colonelpanic.dev nextcloud.octopi.lan"
            - REDIS_HOST=redis
            - REDIS_HOST_PORT=6379
            - OVERWRITEPROTOCOL=http
        depends_on:
            - maindb
            - redis
        secrets:
            - nextcloud_admin_password
            - nextcloud_admin_user
        restart: unless-stopped
        labels:
            - traefik.enable=true
            - traefik.http.routers.nextcloud.rule=Host(`nextcloud.octopi.lan`)
            - traefik.http.routers.nextcloud.entrypoints=web

    travelblog:
        image: wordpress
        container_name: travelblog
        environment:
            WORDPRESS_DB_HOST: maindb
            WORDPRESS_DB_USER: travelblog
            WORDPRESS_DB_PASSWORD: travelblog
            WORDPRESS_DB_NAME: travelblog
        ports:
            - "8082:80"
        networks:
            - cluster
        volumes:
            - travelblog:/var/www/html
        depends_on:
            - maindb
        restart: unless-stopped
        labels:
            - traefik.enable=true
            - traefik.http.routers.travelblog.rule=Host(`travelblog.octopi.lan`)
            - traefik.http.routers.travelblog.entrypoints=web

    gerbera:
        image: gerbera/gerbera
        container_name: gerbera
        privileged: true
        volumes:
            - gerberaconfig:/var/run/gerbera
            - gerberacontent:/content:ro
        networks: 
            lan:
                ipv4_address: 192.168.178.250
        restart: unless-stopped

    pihole:
        image: pihole/pihole:latest
        container_name: pihole
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "67:67/udp"
            - "8083:80/tcp"
        networks:
            - cluster
        environment:
            TZ: 'Europe/Berlin'
            WEBPASSWORD: p1h0l3
        volumes:
            - pihole:/etc/pihole/
            - dnsmasq:/etc/dnsmasq.d/
        restart: unless-stopped
        labels:
            - traefik.enable=true
            - traefik.http.routers.pihole.rule=Host(`pihole.octopi.lan`)
            - traefik.http.routers.pihole.entrypoints=web

    openvpn:
        image: giggio/openvpn-arm
        container_name: openvpn
        cap_add:
            - NET_ADMIN
        ports:
            - "1194:1194/udp"
        volumes:
            - ./openvpn-data/conf:/etc/openvpn
        restart: always

volumes:
    maindb:
        name: maindb
    nextcloud:
        name: nextcloud
    travelblog:
        name: travelblog
    gerberaconfig:
        name: gerberaconfig
    gerberacontent:
        name: gerberacontent
    pihole:
        name: pihole
    dnsmasq:
        name: dnsmasq

secrets:
    nextcloud_admin_user:
        file: ./dockerbuild/nextcloud/secrets/nextcloud_admin_user
    nextcloud_admin_password:
        file: ./dockerbuild/nextcloud/secrets/nextcloud_admin_password
