DROP DATABASE test;
CREATE DATABASE `teamspeak` /*!40100 COLLATE 'utf8_general_ci' */;
USE `teamspeak`;
FLUSH PRIVILEGES;
CREATE USER 'teamspeak'@'%' IDENTIFIED BY 'teamspeak';
GRANT USAGE ON *.* TO 'teamspeak'@'%';
GRANT EXECUTE, SELECT, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, LOCK TABLES  ON `teamspeak`.* TO 'teamspeak'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE DATABASE `travelblog` /*!40100 COLLATE 'utf8_general_ci' */;
USE `travelblog`;
FLUSH PRIVILEGES;
CREATE USER 'travelblog'@'%' IDENTIFIED BY 'travelblog';
GRANT USAGE ON *.* TO 'travelblog'@'%';
GRANT EXECUTE, SELECT, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, LOCK TABLES  ON `travelblog`.* TO 'travelblog'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE DATABASE `nextcloud` /*!40100 COLLATE 'utf8_general_ci' */;
USE `nextcloud`;
FLUSH PRIVILEGES;
CREATE USER 'nextcloud'@'%' IDENTIFIED BY 'nextcloud';
GRANT USAGE ON *.* TO 'nextcloud'@'%';
GRANT EXECUTE, SELECT, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, LOCK TABLES  ON `nextcloud`.* TO 'nextcloud'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;